const LOCAL_DB_KEYS = {
    TOKEN: 'TOKEN',
};

const NAVIGATION_CONSTANTS = {
    LOGIN: 'LOGIN',
    BOTTOM_TAB: 'BOTTOM_TAB',
    HOME: 'HOME',
    CRYPT:'CRYPT',
    DETAIL: 'DETAIL',
    CONVERT: 'CONVERT',

};

 const REDUX_CONSTANTS = {
    SET_TOKEN: 'SET_TOKEN',
};

const HEADER_MODE = {
    HOME: 'HOME',
    DETAIL: 'DETAIL',
    SEARCH: 'SEARCH',
    COLLECTION:'COLLECTION',
    MORE:'MORE',
    EXCHANGES:'EXCHANGES',
};

export const APP_ACTIONS = {
    SHOW_APP_LOADING: 'SHOW_APP_LOADING',
    ADD_PRODUCT_TO_CART:'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART:'REMOVE_PRODUCT_FROM_CART',

};


export {
    LOCAL_DB_KEYS,
    NAVIGATION_CONSTANTS,
    REDUX_CONSTANTS,
    HEADER_MODE,
};
